export const catchAsyncError=()=>{
    return(req,res,next)
}